name: Bug Report
description: Create a bug report to help us improve the plugin
title: '[Bug]: '
labels: bug-triage
assignees: spnda
body:
    - type: input
      id: version
      attributes:
          label: Version of BlockProt
          description: Below fill in which version of the plugin you are using and your Spigot/Minecraft Version.
          placeholder: e.g. 0.3.3, git-Paper-46
      validations:
          required: true
    - type: textarea
      id: actual
      attributes:
          label: Description of the bug
          description: A clear and concise description of what you expected to happen vs what happens. If applicable, add screenshots to help explain your problem.
      validations:
          required: true
    - type: textarea
      id: reproduce
      attributes:
          label: Steps to reproduce
          description: As detailed as possible, please tell us how we can reproduce this.
          placeholder: |
              1. Go to '...'
              2. Click on '....'
              3. See crash
      validations:
          required: true
    - type: textarea
      id: additional_context
      attributes:
          label: Additional context
          description: Add any other context about the problem here.
      validations:
          required: false
