name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'src/main/java/**'
      - 'gradle/**'
      - '**.gradle'
      - '**.gradle.kts'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # Setting any container image breaks actions/checkout@v2.
    # container:
    #   image: openjdk:16-jdk
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - uses: gradle/wrapper-validation-action@v1
      - name: Init CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      # This will also build and therefore test the project.
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
